import { notFound } from 'next/navigation';
import { getInvoiceByPublicToken, getUserById } from '@/lib/db';

export const dynamic = 'force-dynamic';

export default async function PublicInvoice({ params }: { params: { token: string } }) {
  const invoice = await getInvoiceByPublicToken(params.token);
  if (!invoice) notFound();

  const user = await getUserById(invoice.userId);

  return (
    <div className="min-h-screen flex items-center justify-center px-4 py-8">
      <div className="w-full max-w-2xl">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="font-serif italic text-3xl text-paper mb-1">{user?.businessName || 'Fieldline'}</div>
          <div className="font-mono text-[11px] text-paper-mute tracking-wider">INVOICE · {invoice.id.slice(-6).toUpperCase()}</div>
        </div>

        {/* Card */}
        <div className="bg-ink-2 border border-rule rounded-xl overflow-hidden">
          <div className="p-6 sm:p-8 border-b border-rule">
            <div className="flex justify-between items-start gap-4 flex-wrap">
              <div>
                <div className="font-mono text-[10px] text-paper-mute tracking-wider uppercase mb-1">Bill to</div>
                <div className="text-lg text-paper font-medium">{invoice.customerName}</div>
                {invoice.customerEmail && <div className="text-sm text-paper-mute">{invoice.customerEmail}</div>}
              </div>
              <div className="text-right">
                <div className="font-mono text-[10px] text-paper-mute tracking-wider uppercase mb-1">Amount Due</div>
                <div className="font-serif italic text-5xl text-acid leading-none">${invoice.amount.toLocaleString()}</div>
                <StatusBadge status={invoice.status}/>
              </div>
            </div>
          </div>

          {/* Line items */}
          <div className="p-6 sm:p-8 border-b border-rule">
            <div className="font-mono text-[10px] text-paper-mute tracking-wider uppercase mb-4">Items</div>
            <div className="space-y-2">
              {invoice.lineItems.map((li, i) => (
                <div key={i} className="flex justify-between items-start gap-4 py-2 border-b border-rule last:border-0">
                  <div className="text-sm text-paper">{li.description}</div>
                  <div className="font-mono text-sm text-paper-mute whitespace-nowrap">${li.amount.toLocaleString()}</div>
                </div>
              ))}
            </div>
            <div className="mt-4 pt-4 border-t border-rule flex justify-between text-base font-medium">
              <span>Total</span>
              <span className="font-mono text-acid">${invoice.amount.toLocaleString()}</span>
            </div>
          </div>

          {/* Pay action */}
          {invoice.status !== 'paid' && invoice.status !== 'void' && (
            <div className="p-6 sm:p-8 bg-signal/5 border-b border-rule">
              <div className="text-center">
                <div className="text-sm text-paper-mute mb-3">
                  Payment processing not yet active. Please contact {user?.businessName || 'the business'} directly to pay.
                </div>
                {user?.phone && <div className="text-sm text-paper">📞 {user.phone}</div>}
                {user?.email && <div className="text-sm text-paper">✉ {user.email}</div>}
              </div>
            </div>
          )}

          {invoice.status === 'paid' && (
            <div className="p-6 sm:p-8 bg-acid/10 border-b border-rule">
              <div className="text-center">
                <div className="text-acid font-mono text-sm tracking-wider">✓ PAID</div>
                {invoice.paidAt && <div className="text-xs text-paper-mute mt-1">on {new Date(invoice.paidAt).toLocaleDateString()}</div>}
              </div>
            </div>
          )}

          <div className="px-6 py-4 text-center text-[11px] text-paper-dim font-mono tracking-wider">
            Issued {new Date(invoice.createdAt).toLocaleDateString()} · Generated by Fieldline
          </div>
        </div>

        <div className="text-center mt-6 font-mono text-[10px] text-paper-dim tracking-wider">
          Questions? Contact {user?.businessName || 'the business'} directly.
        </div>
      </div>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const map: Record<string, string> = {
    draft: 'bg-paper-dim text-paper-mute',
    sent: 'bg-blue-400/10 text-blue-400 border border-blue-400/30',
    paid: 'bg-acid/10 text-acid border border-acid/30',
    overdue: 'bg-red-400/10 text-red-400 border border-red-400/30',
    void: 'bg-rule text-paper-dim',
  };
  return <span className={`inline-block mt-2 font-mono text-[10px] uppercase px-2 py-0.5 rounded ${map[status] || ''}`}>{status}</span>;
}
